from_latest_tag = false
ignore_merge_commits = true
tag_prefix = "v"
branch_whitelist = ["main"]
pre_bump_hooks = [
  "just test",
  "just clippy",
  "just hack",
  "cargo fmt --all",
  "cargo install cargo-edit",
  "cargo set-version {{version}}",
  "cargo build --release",
]
post_bump_hooks = ["git push", "git push origin v{{version}}"]
pre_package_bump_hooks = []
post_package_bump_hooks = []

[git_hooks.commit-msg]
script = """#!/bin/sh
set -e

echo "[ cargo fmt ]"
cargo fmt --check

echo "[ typos ]"
typos

echo "[ typos $1 ]"
typos $1

echo "[ cog verify ]"
cog verify --file $1
"""

# Configure the generation of the changelog.
[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "mxl-relm4-components"
owner = "x-software-com"
authors = [{ signature = "Andreas", username = "acpiccolo" }]

[commit_types]

[bump_profiles]
